allBirds = [['Aftonfalk  Falco vespertinus']
['Alfagel',  'Clangula hyemalis']
['Alkekung  Alle alle']
['Backsvala  Riparia riparia']
['Bergand  Aythya marila']
['Bergfink  Fringilla montifringilla']
['Berglärka  Eremophila alpestris']
['Berguv  Bubo bubo']
['Bivråk  Pernis apivorus']
['Björktrast  Turdus pilaris']
['Blå kärrhök  Circus cyaneus']
['Blåhake  Luscinia svecica']
['Blåmes  Parus caeruleus']
['Bläsand  Anas penelope']
['Bläsgås  Anser albifrons']
['Bofink  Fringilla coelebs']
['Brun glada  Milvus migrans']
['Brun kärrhök  Circus aeruginosus']
['Brunand  Aythya ferina']
['Brushane  Philomachus pugnax']
['Buskskvätta  Saxicola rubetra']
['Bändelkorsnäbb  Loxia leucoptera']
['Dalripa  Lagopus lagopus']
['Dammsnäppa  Tringa stagnatilis']
['Domherre  Pyrrhula pyrrhula']
['Drillsnäppa  Tringa hypoleucos']
['Dubbelbeckasin  Gallinago media']
['Dubbeltrast  Turdus viscivorus']
['Duvhök  Accipiter gentilis']
['Dvärgbeckasin  Lymnocryptes minimus']
['Dvärgmås  Hydrocoloeus minutus']
['Dvärgsparv  Emberiza pusilla']
['Ejder  Somateria mollissima']
['Enkelbeckasin  Gallinago gallinago']
['Entita  Parus palustris']
['Fasan  Phasanius colchicus']
['Fiskgjuse  Pandion haliaetus']
['Fiskmås  Larus canus']
['Fisktärna  Sterna hirundo']
['Fjällabb  Stercorarius longicaudus']
['Fjällgås  Anser erythropus']
['Fjällpipare  Charadrius morinellus']
['Fjällripa  Lagopus muta']
['Fjälluggla  Nyctea scandiacus']
['Fjällvråk  Buteo lagopus']
['Flodsångare  Locustella fluviatilis']
['Forsärla  Motacilla cinerea']
['Gluttsnäppa  Tringa nebularia']
['Gransångare  Phylloscopus collybita abietinus']
['Gravand  Tadorna tadorna']
['Grå flugsnappare  Muscicapa striata']
['Grågås  Anser anser']
['Gråhakedopping  Podiceps grisegena']
['Gråhäger  Ardea cinerea']
['Gråsiska  Carduelis flammea']
['Gråsparv  Passer domesticus']
['Gråspett  Picus canus']
['Gråtrut  Larus argentatus']
['Gräsand  Anas platyrhynchos']
['Gräshoppsångare  Locustella naevia']
['Grönbena  Tringa glareola']
['Grönfink  Carduelis chloris']
['Gröngöling  Picus viridis']
['Grönsiska  Carduelis spinus']
['Grönsångare  Phylloscopus sibilatrix']
['Gulsparv  Emberiza citrinella']
['Gulärla  Motacilla flava']
['Gärdsmyg  Troglodytes troglodytes']
['Gök  Cuculus canorus']
['Göktyta  Jynx torquilla']
['Halsbandsflugsnappare  Ficedula albicollis']
['Havssula  Sula bassana']
['Havstrut  Larus marinus']
['Havsörn  Haliaeetus albicilla']
['Hornuggla  Asio otus']
['Hussvala  Delichon urbica']
['Hämpling  Carduelis cannabina']
['Härmsångare  Hippolais icterina']
['Höksångare  Sylvia nisoria']
['Hökuggla  Surnia ulula']
['Jaktfalk  Falco rusticolus']
['Jorduggla  Asio flammeus']
['Järnsparv  Prunella modularis']
['Järpe  Bonasa bonasia']
['Kaja  Corvus monedula']
['Kanadagås  Branta canadensis']
['Kattuggla  Strix aluco']
['Kentsk tärna  Sterna sandvicensis']
['Knipa  Bucephala clangula']
['Knölsvan  Cygnus olor']
['Koltrast  Turdus merula']
['Kornknarr  Crex crex']
['Kornsparv  Emberiza calandra']
['Korp  Corvus corax']
['Kricka  Anas crecca']
['Kråka  Corvus corone']
['Kungsfiskare  Alcedo atthis']
['Kungsfågel  Regulus regulus']
['Kungsfågelsångare  Phylloscopus proregulus']
['Kungsörn  Aquila chrysaetos']
['Kustpipare  Pluvialis squatarola']
['Kustsnäppa  Calidris canutus']
['Kärrsnäppa  Calidris alpina']
['Kärrsångare  Acrocephalus palustris']
['Ladusvala  Hirundo rustica']
['Lappmes  Parus cinctus']
['Lappsparv  Calcarius lapponicus']
['Lappuggla  Strix nebulosa']
['Lavskrika  Perisorenus infaustus']
['Ljungpipare  Pluvialis apricaria']
['Lundsångare  Phylloscopus trochiloides']
['Lärkfalk  Falco subbuteo']
['Lövsångare  Phylloscopus trochilus']
['Mindre flugsnappare  Ficedula parva']
['Mindre hackspett  Dendrocopos minor']
['Mindre korsnäbb  Loxia curvirostra']
['Mindre strandpipare  Charadrius dubius']
['Morkulla  Scolopax rusticola']
['Mosnäppa  Calidris temminckii']
['Myrsnäppa  Limicola falcinellus']
['Myrspov  Limosa lapponica']
['Nattskärra  Caprimulgus europaeus']
['Nordsångare  Phylloscopus borealis']
['Näktergal  Luscinia luscinia']
['Nötkråka  Nucifraga caryocatactes']
['Nötskrika  Garrulus glandarius']
['Nötväcka  Sitta europaea']
['Ormvråk  Buteo buteo']
['Orre  Lyrurus tetrix']
['Ortolansparv  Emberiza hortulana']
['Pilfink  Passer montanus']
['Pilgrimsfalk  Falco peregrinus']
['Prutgås  Branta bernicla']
['Pungmes  Remiz pendulinus']
['Pärluggla  Aegolius funereus']
['Rapphöna  Perdix perdix']
['Ringduva  Columba palumbus']
['Ringtrast  Turdus torquatus']
['Rosenfink  Carpodacus erythrinus']
['Roskarl  Arenaria interpres']
['Råka  Corvus frugilegus']
['Röd glada  Milvus milvus']
['Rödbena  Tringa totanus']
['Rödhake  Erithacus rubecula']
['Rödspov  Limosa limosa']
['Rödstjärt  Phoenicurus phoenicurus']
['Rödstrupig piplärka  Anthus cervinus']
['Rödvingetrast  Turdus iliacus']
['Rördrom  Botaurus stellaris']
['Rörhöna  Gallinula chloropus']
['Rörsångare  Acrocephalus scirpaceus']
['Salskrake  Mergellus albellus']
['Sidensvans  Bombycilla garrulus']
['Sillgrissla  Uria aalge']
['Silltrut  Larus fuscus']
['Silvertärna  Sterna paradisaea']
['Sjöorre  Melanitta nigra']
['Skata  Pica pica']
['Skedand  Anas clypeata']
['Skogsduva  Columba oenas']
['Skogssnäppa  Tringa ochropus']
['Skrattmås  Larus ridibundus']
['Skräntärna  Sterna caspia']
['Skäggdopping  Podiceps cristatus']
['Skäggmes  Panurus biarmicus']
['Skärfläcka  Recurvirostra avosetta']
['Skärpiplärka  Anthus petrosus']
['Skärsnäppa  Calidris maritima']
['Slaguggla  Strix uralensis']
['Smalnäbbad simsnäppa  Phalaropus lobatus']
['Smådopping  Tachybaptus ruficollis']
['Småfläckig sumphöna  Porzana porzana']
['Smålom  Gavia stellata']
['Småskrake  Mergus serrator']
['Småsnäppa  Calidris minuta']
['Småspov  Numenius phaeopus']
['Småtärna  Sterna albifrons']
['Snatterand  Anas strepera']
['Snösparv  Plectrophenax nivalis']
['Sommargylling  Oriolus oriolus']
['Sothöna  Fulica atra']
['Sparvhök  Accipiter nisus']
['Sparvuggla  Glaucidium passerinum']
['Spetsbergsgås  Anser brachyrhynchus']
['Spillkråka  Dryocopus martius']
['Spovsnäppa  Calidris ferruginea']
['Stare  Sturnus vulgaris']
['Steglits  Carduelis carduelis']
['Stenfalk  Falco columbarius']
['Stenknäck  Coccothraustes coccothraustes']
['Stenskvätta  Oenanthe oenanthe']
['Stjärtand  Anas acuta']
['Stjärtmes  Aegithalos caudatus']
['Storlom  Gavia arctica']
['Storskarv  Phalacrocorax carbo']
['Storskrake  Mergus merganser']
['Storspov  Numenius arquata']
['Strandskata  Haematopus ostralegus']
['Stripgås  Anser indicus']
['Strömstare  Cinclus cinclus']
['Större hackspett  Dendrocopos major']
['Större korsnäbb  Loxia pytyopsittacus']
['Större strandpipare  Charadrius hiaticula']
['Svart rödstjärt  Phoenicurus ochruros']
['Svarthakedopping  Podiceps auritus']
['Svarthalsad dopping  Podiceps nigricollis']
['Svarthätta  Sylvia atricapilla']
['Svartmes  Parus ater']
['Svartsnäppa  Tringa erythropus']
['Svartvit flugsnappare  Ficedula hypoleuca']
['Svärta  Melanitta fusca']
['Sånglärka  Alauda arvensis']
['Sångsvan  Cygnus cygnus']
['Sädesärla  Motacilla alba']
['Sädgås  Anser fabalis']
['Sävsparv  Emberiza schoeniclus']
['Sävsångare  Acrocephalus schoenobaenus']
['Talgoxe  Parus major']
['Tallbit  Pinicola enucleator']
['Talltita  Parus montanus']
['Taltrast  Turdus philomelos']
['Tamduva  Columba livia']
['Tjäder  Tetrao urogallus']
['Tobisgrissla  Cepphus grylle']
['Tofsmes  Parus cristatus']
['Tofsvipa  Vanellus vanellus']
['Tordmule  Alca torda']
['Tornfalk  Falco tinnunculus']
['Tornseglare  Apus apus']
['Tornuggla  Tyto alba']['Trana  Grus grus']['Trastsångare  Acrocephalus arundinaceus']
['Tretåig hackspett  Picoides tridactylus']
['Trädgårdssångare  Sylvia borin']['Trädkrypare  Certhia familiaris']['Trädlärka  Lullula arborea']['Trädpiplärka  Anthus trivialis']
['Turkduva  Streptopelia decaocto']['Turturduva  Streptopelia turtur']['Törnskata  Lanius collurio']['Törnsångare  Sylvia communis']
['Vaktel  Coturnix coturnix']['Varfågel  Lanius excubitor']
['Vassångare  Locustella luscinioides']['Vattenrall  Rallus aquaticus']['Videsparv  Emberiza rustica']['Vigg  Aythya fuligula']['Vinterhämpling  Carduelis flavirostris']
['Vit stork  Ciconia ciconia']['Vitkindad gås  Branta leucopsis']['Årta  Anas querquedula']['Ängshök  Circus pygargus']
['Ängspiplärka  Anthus pratensis']['Ärtsångare  Sylvia curruca']]
print(allBirds)
